#!/usr/bin/env bash

set -euo pipefail

VPS_USER="${VPS_USER:-}"
VPS_HOST="${VPS_HOST:-}"
REMOTE="${VPS_USER}@${VPS_HOST}"

if [[ -z "$VPS_USER" || -z "$VPS_HOST" ]]; then
  echo "VPS_USER and VPS_HOST must be set." >&2
  exit 1
fi

EXPORT_DAYS="${EXPORT_DAYS:-1}"
EXPORT_START_TS="${EXPORT_START_TS:-}"
EXPORT_END_TS="${EXPORT_END_TS:-}"
EXPORT_SERIES_START_TS="${EXPORT_SERIES_START_TS:-}"
EXPORT_SERIES_END_TS="${EXPORT_SERIES_END_TS:-}"
EXPORT_CHUNK_HOURS="${EXPORT_CHUNK_HOURS:-24}"

ssh "$REMOTE" \
  "EXPORT_DAYS='$EXPORT_DAYS' \
   EXPORT_START_TS='$EXPORT_START_TS' \
   EXPORT_END_TS='$EXPORT_END_TS' \
   EXPORT_SERIES_START_TS='$EXPORT_SERIES_START_TS' \
   EXPORT_SERIES_END_TS='$EXPORT_SERIES_END_TS' \
   EXPORT_CHUNK_HOURS='$EXPORT_CHUNK_HOURS' \
   /opt/urban-pulse/export_vehicle_positions.sh"
